---
name: github
provider: github.com
repository: docker-hugo
url: https://github.com/cardboardci/docker-hugo
clone:
  ssh: git@github.com:cardboardci/docker-hugo.git
  https: https://github.com/cardboardci/docker-hugo.git